version: "3.7"
name: "fifo"
services:
  fifo:
    build:
      context: .
      dockerfile: Dockerfile-c
    restart: unless-stopped
    container_name: fifo-c
    ports:
      - "5124:5124"
    environment:
      - PORT=5124
      - PENDING=512
      - MAX_BUF=2048
      - REUSE=0
      - FORWARD=localhost:5111
      - API_KEY=1
    extra_hosts:
    - "host.docker.internal:host-gateway"
